application: hale-aurora-94017
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: home.app

- url: /index\.html
  script: home.app

- url: /charts
  static_dir: charts

- url: /data-js
  static_dir: data-js

- url: /service
  script: service.app

- url: /style
  static_dir: style

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
