application: bustling-dynamo-253414
#application: hale-aurora-94017
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: home.app

- url: /index\.html
  script: home.app

- url: /charts
  static_dir: charts
  # d3

- url: /data-js
  static_dir: data-js  
  # json files

- url: /js
  static_dir: js 
  # js files

- url: /htmls
  static_dir: htmls
  # html files

- url: /shape_svg
  static_dir: shape_svg
  # js files
- url: /markdown-html
  static_dir: markdown-html

- url: /service
  script: service.app
  # pieprasījumu apstrāde, REST

- url: /style
  static_dir: style

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
